
const airports_dict = {
    'LHR': 'London, LHR',
    'LGW': 'London (Gatwick), LGW',  
    'STN': 'London (Stansted), STN',  
    'CDG': 'Paris (Charles de Gaulle), CDG',
    'ORY': 'Paris (Orly), ORY',  
    'FRA': 'Frankfurt, FRA',
    'AMS': 'Amsterdam, AMS',
    'MAD': 'Madrid, MAD',
    'BCN': 'Barcelona, BCN',
    'FCO': 'Rome, FCO',
    'MUC': 'Munich, MUC',
    'ZRH': 'Zurich, ZRH',
    'VIE': 'Vienna, VIE',
    'CPH': 'Copenhagen, CPH',
    'DUB': 'Dublin, DUB',
    'HEL': 'Helsinki, HEL',
    'BRU': 'Brussels, BRU',
    'OSL': 'Oslo, OSL',
    'ARN': 'Stockholm, ARN',
    'MXP': 'Milan, MXP',
    'ATH': 'Athens, ATH',
    'LIS': 'Lisbon, LIS',
    'SVO': 'Moscow (Sheremetyevo), SVO',
    'DME': 'Moscow (Domodedovo), DME',  
    'LED': 'Saint Petersburg, LED',
    'WAW': 'Warsaw, WAW',
    'PRG': 'Prague, PRG',
    'BUD': 'Budapest, BUD',
    'TXL': 'Berlin (Tegel), TXL',  
    'BER': 'Berlin (Brandenburg), BER',  
    'SXF': 'Berlin (Schönefeld), SXF',  
    'MAN': 'Manchester, MAN',
    'DUS': 'Düsseldorf, DUS',
    'HAM': 'Hamburg, HAM',
    'PMI': 'Palma de Mallorca, PMI',
    'AGP': 'Málaga, AGP',
    'VCE': 'Venice, VCE',
    'NAP': 'Naples, NAP',
    'NCE': 'Nice, NCE',
    'GVA': 'Geneva, GVA',
    'LUX': 'Luxembourg, LUX',
    'LJU': 'Ljubljana, LJU',
    'SOF': 'Sofia, SOF',
    'OTP': 'Bucharest, OTP',
    'BTS': 'Bratislava, BTS',
    'ZAG': 'Zagreb, ZAG',
    'BEG': 'Belgrade, BEG',
    'SKG': 'Thessaloniki, SKG',
    'TSF': 'Treviso, TSF',
    'CTA': 'Catania, CTA',
    'ATL': 'Atlanta, ATL',
    'LAX': 'Los Angeles, LAX',
    'ORD': 'Chicago, ORD',
    'DFW': 'Dallas/Fort Worth, DFW',
    'JFK': 'New York (JFK), JFK',
    'DEN': 'Denver, DEN',
    'SFO': 'San Francisco, SFO',
    'SEA': 'Seattle, SEA',
    'MIA': 'Miami, MIA',
    'LAS': 'Las Vegas, LAS',
    'PHX': 'Phoenix, PHX',
    'IAH': 'Houston, IAH',
    'MSP': 'Minneapolis-Saint Paul, MSP',
    'BOS': 'Boston, BOS',
    'EWR': 'New York (Newark), EWR',  
    'DTW': 'Detroit, DTW',
    'CLT': 'Charlotte, CLT',
    'LGA': 'New York (LaGuardia), LGA',  
    'BWI': 'Baltimore, BWI',
    'SAN': 'San Diego, SAN',
}

export default airports_dict;