airports_list = [
    "LHR - London Heathrow Airport",
    "CDG - Charles de Gaulle Airport (Paris)",
    "FRA - Frankfurt Airport",
    "AMS - Amsterdam Schiphol Airport",
    "MAD - Adolfo Suárez Madrid-Barajas Airport",
    "BCN - Barcelona-El Prat Airport",
    "FCO - Leonardo da Vinci–Fiumicino Airport (Rome)",
    "MUC - Munich Airport",
    "LGW - London Gatwick Airport",
    "ZRH - Zurich Airport",
    "VIE - Vienna International Airport",
    "CPH - Copenhagen Airport",
    "DUB - Dublin Airport",
    "HEL - Helsinki Airport",
    "BRU - Brussels Airport",
    "OSL - Oslo Gardermoen Airport",
    "ARN - Stockholm Arlanda Airport",
    "MXP - Milan Malpensa Airport",
    "ATH - Athens International Airport",
    "LIS - Lisbon Humberto Delgado Airport",
    "ORY - Paris Orly Airport",
    "SVO - Sheremetyevo International Airport (Moscow)",
    "DME - Domodedovo International Airport (Moscow)",
    "LED - Pulkovo Airport (Saint Petersburg)",
    "WAW - Warsaw Chopin Airport",
    "PRG - Václav Havel Airport Prague",
    "BUD - Budapest Ferenc Liszt International Airport",
    "TXL - Berlin Tegel Airport (closed, but historically significant)",
    "BER - Berlin Brandenburg Airport",
    "SXF - Berlin Schönefeld Airport (now part of Brandenburg)",
    "MAN - Manchester Airport",
    "STN - London Stansted Airport",
    "DUS - Düsseldorf Airport",
    "HAM - Hamburg Airport",
    "PMI - Palma de Mallorca Airport",
    "AGP - Málaga Airport",
    "VCE - Venice Marco Polo Airport",
    "NAP - Naples International Airport",
    "NCE - Nice Côte d'Azur Airport",
    "GVA - Geneva Airport",
    "LUX - Luxembourg Airport",
    "LJU - Ljubljana Jože Pučnik Airport",
    "SOF - Sofia Airport",
    "OTP - Henri Coandă International Airport (Bucharest)",
    "BTS - Bratislava Airport",
    "ZAG - Zagreb Airport",
    "BEG - Belgrade Nikola Tesla Airport",
    "SKG - Thessaloniki Airport",
    "TSF - Treviso Airport",
    "CTA - Catania Fontanarossa Airport"
]
